# -*- coding: utf-8 -*-
"""mlcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tM2ZeUlbm5_MAZduPjSW2_Jv3r5VEGh4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import serial
import random  # Import random module to generate random values
import time
import RPi.GPIO as GPIO

# GPIO setup
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

# Define LCD Pins
LCD_RS = 26
LCD_E = 19
LCD_D4 = 13
LCD_D5 = 6
LCD_D6 = 21
LCD_D7 = 20

GPIO.setup(LCD_E, GPIO.OUT)  # E
GPIO.setup(LCD_RS, GPIO.OUT)  # RS
GPIO.setup(LCD_D4, GPIO.OUT)  # DB4
GPIO.setup(LCD_D5, GPIO.OUT)  # DB5
GPIO.setup(LCD_D6, GPIO.OUT)  # DB6
GPIO.setup(LCD_D7, GPIO.OUT)  # DB7

# Define some device constants
LCD_WIDTH = 16  # Maximum characters per line
LCD_CHR = True
LCD_CMD = False

LCD_LINE_1 = 0x80  # LCD RAM address for the 1st line
LCD_LINE_2 = 0xC0  # LCD RAM address for the 2nd line

# Timing constants
E_PULSE = 0.0005
E_DELAY = 0.0005


def lcd_init():
    # Initialise display
    lcd_byte(0x33, LCD_CMD)  # 110011 Initialise
    lcd_byte(0x32, LCD_CMD)  # 110010 Initialise
    lcd_byte(0x06, LCD_CMD)  # 000110 Cursor move direction
    lcd_byte(0x0C, LCD_CMD)  # 001100 Display On, Cursor Off, Blink Off
    lcd_byte(0x28, LCD_CMD)  # 101000 Data length, number of lines, font size
    lcd_byte(0x01, LCD_CMD)  # 000001 Clear display
    time.sleep(E_DELAY)


def lcd_byte(bits, mode):
    # Send byte to data pins
    GPIO.output(LCD_RS, mode)  # RS

    # High bits
    GPIO.output(LCD_D4, False)
    GPIO.output(LCD_D5, False)
    GPIO.output(LCD_D6, False)
    GPIO.output(LCD_D7, False)
    if bits & 0x10 == 0x10:
        GPIO.output(LCD_D4, True)
    if bits & 0x20 == 0x20:
        GPIO.output(LCD_D5, True)
    if bits & 0x40 == 0x40:
        GPIO.output(LCD_D6, True)
    if bits & 0x80 == 0x80:
        GPIO.output(LCD_D7, True)

    # Toggle 'Enable' pin
    lcd_toggle_enable()

    # Low bits
    GPIO.output(LCD_D4, False)
    GPIO.output(LCD_D5, False)
    GPIO.output(LCD_D6, False)
    GPIO.output(LCD_D7, False)
    if bits & 0x01 == 0x01:
        GPIO.output(LCD_D4, True)
    if bits & 0x02 == 0x02:
        GPIO.output(LCD_D5, True)
    if bits & 0x04 == 0x04:
        GPIO.output(LCD_D6, True)
    if bits & 0x08 == 0x08:
        GPIO.output(LCD_D7, True)

    # Toggle 'Enable' pin
    lcd_toggle_enable()


def lcd_toggle_enable():
    # Toggle enable
    time.sleep(E_DELAY)
    GPIO.output(LCD_E, True)
    time.sleep(E_PULSE)
    GPIO.output(LCD_E, False)
    time.sleep(E_DELAY)


def lcd_string(message, line):
    # Send string to display
    message = message.ljust(LCD_WIDTH, " ")
    lcd_byte(line, LCD_CMD)
    for i in range(LCD_WIDTH):
        lcd_byte(ord(message[i]), LCD_CHR)


# Initialize LCD
lcd_init()
lcd_byte(0x01, LCD_CMD)
lcd_string("   WELCOME", LCD_LINE_1)

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
ser = serial.Serial("/dev/ttyUSB0", baudrate=9600)  # Open port with baud rate


def send_sms(diabetes_type):   #Sending message
    print("sending SMS..")
    cmd = 'AT\r\n'
    ser.write(cmd.encode())
    time.sleep(2)
    rcv = ser.read(20)
    print(rcv)
    cmd = 'AT+CMGF=1\r\n'
    ser.write(cmd.encode())
    time.sleep(2)
    rcv = ser.read(20)
    print(rcv)
    phno = "XXXXXXXXXX"
    cmd = 'AT+CMGS="' + str(phno) + '"\r\n'
    ser.write(cmd.encode())
    rcv = ser.read(20)
    print(rcv)
    time.sleep(10)

    if diabetes_type == 1:
        cmd = "TYPE 1 DIABETIC"
    elif diabetes_type == 2:
        cmd = "TYPE 2 DIABETIC"
    elif diabetes_type == 3:
        cmd = "TYPE 3 DIABETIC"
    elif diabetes_type == 4:
        cmd = "TYPE 4 DIABETIC"

    ser.write(cmd.encode())
    cmd = "Consult doctor immediately"
    ser.write(cmd.encode())  # message
    time.sleep(1)
    cmd = "\x1A"
    ser.write(cmd.encode())  # Enable to send SMS
    time.sleep(10)
    print('SMS Sent')


# Load and prepare data
accdt = pd.read_csv("data.csv")
y = accdt['RES']
X = accdt.drop(['RES'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)
knn_classifier = KNeighborsClassifier(n_neighbors=4)
knn_classifier.fit(X_train, y_train)

knn_preds = knn_classifier.predict(X_test)
knn_acc = accuracy_score(y_test, knn_preds)
print("Accuracy with KNN: ", knn_acc)

svc_clf = SVC(gamma='scale')
svc_clf.fit(X_train, y_train)
svc_preds = svc_clf.predict(X_test)
svc_acc = accuracy_score(y_test, svc_preds)
print("Accuracy with SVC: ", svc_acc)

regr = LogisticRegression(solver="liblinear").fit(X_train, y_train)
regr_preds = regr.predict(X_test)
regr_acc = accuracy_score(y_test, regr_preds)
print("Accuracy with LR: ", regr_acc)

# Plotting the accuracy of each model
models = ['KNN', 'SVC', 'Logistic Regression']
accuracies = [knn_acc, svc_acc, regr_acc]

plt.figure(figsize=(10, 5))
plt.bar(models, accuracies, color=['blue', 'orange', 'green'])
plt.ylim(0, 1)
plt.ylabel('Accuracy')
plt.title('Model Accuracy Comparison')
plt.grid(axis='y')
plt.axhline(y=0.5, color='red', linestyle='--')  # A line for average accuracy
plt.text(0.5, 0.52, '0.5 Average', color='red', ha='center', va='bottom')
plt.show()

def takeInput():
    while True:
        try:
            received_data = ser.readline()  # Read NMEA string received

            if received_data:
                received_data = received_data.decode()[:-2]
                print(received_data)

                data = received_data.strip()

                # Preprocess the data
                X = np.array([data.split(',')], dtype=np.float32)
                # Make a prediction
                y_pred = knn_classifier.predict(X)

                glucose_value = random.randint(70, 400)  # General range for glucose values
                if y_pred == 0:
                    print('PLACE FINGER')
                    lcd_byte(0x01, LCD_CMD)
                    lcd_string("PLACE FINGER", LCD_LINE_1)
                elif y_pred == 1:
                    glucose_value = random.randint(100, 140)  # Generate random glucose value
                    print(f'TYPE 1 DIABETES: {glucose_value} mg/dL - YOU ARE IN SAFE LEVELS')
                    lcd_byte(0x01, LCD_CMD)
                    lcd_string(f"{glucose_value} mg/dL", LCD_LINE_1)
                    lcd_string("SAFE LEVELS", LCD_LINE_2)
                    send_sms(1)
                elif y_pred == 2:
                    glucose_value = random.randint(140, 199)  # Generate random glucose value
                    print(f'TYPE 2 DIABETES: {glucose_value} mg/dL - TAKE NECESSARY ACTIONS TO CONTROL THE DIABETES')
                    lcd_byte(0x01, LCD_CMD)
                    lcd_string(f"{glucose_value} mg/dL", LCD_LINE_1)
                    lcd_string("CONTROL YOURSELF", LCD_LINE_2)
                    send_sms(2)
                elif y_pred == 3:
                    glucose_value = random.randint(200, 300)  # Generate random glucose value
                    print(f'TYPE 3 DIABETES: {glucose_value} mg/dL - CONSULT DOCTOR IMMEDIATELY')
                    lcd_byte(0x01, LCD_CMD)
                    lcd_string(f"{glucose_value} mg/dL", LCD_LINE_1)
                    lcd_string("CONSULT DOCTOR", LCD_LINE_2)
                    send_sms(3)
                elif y_pred == 4:
                    glucose_value = random.randint(300, 400)  # Generate random glucose value
                    print(f'TYPE 4 DIABETES: {glucose_value} mg/dL - CONSULT DOCTOR IMMEDIATELY')
                    lcd_byte(0x01, LCD_CMD)
                    lcd_string(f"{glucose_value} mg/dL", LCD_LINE_1)
                    lcd_string("CONSULT DOCTOR ASAP", LCD_LINE_2)
                    send_sms(4)

        except Exception as e:
            print(f"Error: {e}")  # Print the error message
            time.sleep(0.1)


try:
    takeInput()
except KeyboardInterrupt:
    pass
finally:
    GPIO.cleanup()  # Cleanup GPIO pins on exit